name: UCFGs caching test
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disable shallow clones
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install scanner
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        shell: powershell
        run: |
          # $sqHostUrl = "http://34.140.200.96"
          # $sqToken = "${{ secrets.SQ_EU_TOKEN }}"
          $sqHostUrl = "http://34.30.43.46"
          $sqToken = "${{ secrets.SQ_US_TOKEN }}"

          $out = New-Object byte[] 500000000
          (New-Object Random).NextBytes($out)
          [IO.File]::WriteAllBytes('C:\Temp\ucfg_cs2.zip', $out)

          $projectKey = "nodatime-ucfg-caching-github"
          .\.sonar\scanner\dotnet-sonarscanner begin /k:$projectKey /d:sonar.login=$sqToken /d:sonar.host.url=$sqHostUrl /d:sonar.verbose=true
          dotnet build .\src\NodaTime.sln
          Measure-Command { 
              .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login=$sqToken 
          }
